name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3


      # Build the Docker image
      - name: Build Docker image BACK
        run: |
          docker build -t weeding-back:latest ./back
      # Build the Docker image
      - name: Build Docker image FRONT
        run: |
          docker build -t weeding-front:latest ./weeding-front

      # (Optional) Push the image to Docker Hub
      - name: Push Docker image
        run: |
          docker tag my-docker-image:latest ${{ secrets.DOCKER_USERNAME }}/my-docker-image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-docker-image:latest
